### ISSUE TITLE
Problem with notifications

### ISSUE THREAD

**Issue by adrien-barret** [geerlingguy/awx-container#16]
Hi,

I tried to put a webhook for Microsoft Teams and a slack (test if the problem was the webhook or the notifications....) but the both failed when I try the notifications.
No log on the host or on the docker at /var/log/tower/ all directories are empty.

Any Idea ?

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
