### ISSUE TITLE
Docker swarm support

### ISSUE THREAD

**Issue by lucaslan** [geerlingguy/awx-container#17]
Hello, 
I'm trying to deploy AWX in a swarm cluster using stack and it doesn't work well.

I already changed the links to a network using the overlay driver... 
Did you already tried this?

**Comment by DBLaci** [comment]
I used the compose found in this repo to deploy awx stack to swarm. It went smooth without any problem.

I later modified 2 thins (neither has anything to do with your question): postgres volume on node (this is a swarm cluster with only one node, you may need to use node label constraints to bind it to a specific node):

in the postgres service:

```
    volumes:
      - /srv/awx/postgresql/data:/var/lib/postgresql/data
```

The other change is I tried with the ansible/awx_* images (and it works too).

So I confirm the docker-compose works with swarm well. What's your problem?

**Comment by dnc92301** [comment]
Have you tried setting up ssl reverse proxy within your stack docker compose file ?

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
