### ISSUE TITLE
How I can change port from 80?

### ISSUE THREAD

**Issue by nalcheg** [geerlingguy/awx-container#18]
If I change host port in awx_web, for example it be like
```
  awx_web:
....
    ports:
      - "33380:8052"
```
Web interface ceases to work, with this errors
```
(index):12 GET http://127.0.0.1:33380/static/css/vendor.c7c34fcde5e8a885ab9c.css net::ERR_ABORTED
(index):19 GET http://127.0.0.1:33380/static/js/app.c7c34fcde5e8a885ab9c.js net::ERR_ABORTED
(index):17 GET http://127.0.0.1:33380/static/js/vendor.c7c34fcde5e8a885ab9c.js net::ERR_ABORTED
(index):14 GET http://127.0.0.1:33380/static/css/app.c7c34fcde5e8a885ab9c.css net::ERR_ABORTED
(index):19 GET http://127.0.0.1:33380/static/js/app.c7c34fcde5e8a885ab9c.js net::ERR_ABORTED

```

**Comment by nalcheg** [comment]
folder /var/lib/awx/public/static/ of awx_web container is empty in this case

**Comment by smiller171** [comment]
@nalcheg Are you not seeing this issue on port 80? I'm seeing this issue even on port 80.

**Comment by smiller171** [comment]
Fixed for me if I use the geerlingguy images instead of the ansible ones

**Comment by nalcheg** [comment]
I began to use https://github.com/ansible/awx/blob/devel/INSTALL.md#docker-or-docker-compose
