### ISSUE TITLE
Scheduling is broken

### ISSUE THREAD

**Issue by JSkier21** [geerlingguy/awx-container#19]
Scheduling is completely broken in this containerized version. Would you be willing to adopt the patch from upstream? https://github.com/ansible/awx/pull/244

**Comment by JSkier21** [comment]
Rebuilding on a different machine and it works. I'll try that on the machine in question.

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
