### ISSUE TITLE
I get this when try to load my inventory through aws

### ISSUE THREAD

**Issue by ssarkarnetip** [geerlingguy/awx-container#25]
django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known

I have all of my system configured on the localhost.  Everything else is working fine.  I can not seem to load any inventory even through git.  Inventory does load manually put it.

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
