### ISSUE TITLE
Discussion: Migration Paths for AWX

### ISSUE THREAD

**Issue by FloThinksPi** [geerlingguy/awx-container#30]
Maybe this Project could be extended to provide a update path for the AWX containers somehow ?

As For AWX, it seems that a productive use is impossible, because awx does not provide migration paths to higher versions, thus no updates in production.

https://github.com/ansible/awx/issues/138
https://groups.google.com/forum/#!msg/awx-project/PQLxKl5Rj9s/UGy-3VaCCQAJ 

If the aim of this Project is a productive deployment of awx, there should be a migration path of the main AWX releases (e.g 1.0.2 -> 1.0.3 ). If not , close this 😄.

Whats you opinion on that ?

**Comment by geerlingguy** [comment]
This particular project is currently a 'quick start demo' type of AWX setup... I definitely won't have the time/ability to build AWX migration/upgrade paths in this project—efforts should be directed upstream to the AWX project.

I do have my own container images on Docker Hub locked at a stable point, though, and only upgrade once every few stable releases. If you can survive without the latest and greatest... it could be possible to hang back on older image versions.

**Comment by FloThinksPi** [comment]
@geerlingguy 
Yea i also started freezing 1.0.2 and manually patching some important Bugfixes into my branch. 
you say you upgrade your version to a stable Release then, but as it seems from that ticket there wont be a upgrade path in the near future for any upcoming version. At least not from 1.0.2 or any version we froze by ourselves :S

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
