### ISSUE TITLE
No proper login page after first docker-compose up

### ISSUE THREAD

**Issue by scorputty** [geerlingguy/awx-container#31]
Hi,

When I do docker-compose up -d (on OSX) I see this in my (chrome) browser:

![image](https://user-images.githubusercontent.com/9146733/37140822-50118aa4-22b3-11e8-97b2-c9e1382fb345.png)

First I thought it's because awx_task was still busy but even if I wait till it stops the page stays the same.

If I do a docker-compose restart it all works:

![image](https://user-images.githubusercontent.com/9146733/37140906-91adee3a-22b3-11e8-88dc-89a18bcf2c72.png)

Any idea why this happens?

**Comment by nsaud01** [comment]
+1

**Comment by dmsimard** [comment]
I got this too. Thanks for the docker-compose restart trick.

Edit: I didn't troubleshoot too much but at least as far as I can tell, it looks like some assets aren't found. Looking at the page source, I saw the following:

```
<link href="/static/css/vendor.3e674a3ba3212cd5dd22.css" rel="stylesheet" />
<link href="/static/css/app.763b47aa28c5e5fd8aac.css" rel="stylesheet" />
<script src="/static/js/vendor.3e674a3ba3212cd5dd22.js"></script>
<script src="/static/js/app.763b47aa28c5e5fd8aac.js"></script>
```

They all end up not found (404).

**Comment by srflaxu40** [comment]
Also getting.

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
