### ISSUE TITLE
Q: is it possible to build lxd into the container?

### ISSUE THREAD

**Issue by chuegel** [geerlingguy/awx-container#32]
Hi,

I´m wondering if you could build lxd into the container as 99% of my hosts are lxd containers, thus using lxd as `ansible_connection`

Thx

**Comment by timaklnz** [comment]
+1 on this - let me know!

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
