### ISSUE TITLE
What's the trick to upgrade Ansible?

### ISSUE THREAD

**Issue by SimplySeth** [geerlingguy/awx-container#33]
I'm using `latest` image tag 

I tried:

```
/var/lib/awx/venv/ansible/bin/pip install --upgrade ansible

```

and I get ... 

```
Error: [('/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pycparser-2.17-py2.7.egg-info/PKG-INFO',
```

Thanks

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
