### ISSUE TITLE
Run awx_web and awx_task not as root?

### ISSUE THREAD

**Issue by KenJusticeJr** [geerlingguy/awx-container#38]
Is it wise to run the awx_web and awx_task containers as root (as defined in the docker-compose file)? Would it be possible to run them otherwise? Thanks!

**Comment by lautaromss** [comment]
Hello, I'm having the same doubt. We can't run containers as root in OpenShift. Is it possible to run it without root?

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
