### ISSUE TITLE
Helm chart for awx

### ISSUE THREAD

**Issue by joaocc** [geerlingguy/awx-container#42]
Hi,
Are there any plans to create a helm chart for this image?
Thx

**Comment by geerlingguy** [comment]
@joaocc - Unfortunately, not right now; I have not yet worked with putting AWX inside any of my K8s clusters, and until I do so I won't have the time to spend on it.

I'll leave this open though in case anyone else wants to take a stab at it. Would be awesome to have an easy way to get AWX into a cluster!

**Comment by joaocc** [comment]
Thx for you answer. There is currently a PR for an AWX chart to helm/incubator at  https://github.com/helm/charts/pull/6106, but I believe is for the "standard" AWX deployment

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
