### ISSUE TITLE
geerlingguy.repo-epel error

### ISSUE THREAD

**Issue by Harshal-20** [geerlingguy/awx-container#48]
When trying to build image for AWX, getting error for below task.  It looks like geerlingguy.repo-epel refers to https://dl.fedoraproject.org/pub/epel/epel-release-latest-NA.noarch.rpm which is not found.

TASK [geerlingguy.repo-epel : Install EPEL repo.] ******************************
FAILED - RETRYING: Install EPEL repo. (5 retries left).
FAILED - RETRYING: Install EPEL repo. (4 retries left).
FAILED - RETRYING: Install EPEL repo. (3 retries left).
FAILED - RETRYING: Install EPEL repo. (2 retries left).
FAILED - RETRYING: Install EPEL repo. (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 5, "changed": false, "failed": true,                  "msg": "Failure downloading https://dl.fedoraproject.org/pub/epel/epel-release-                 latest-NA.noarch.rpm, HTTP Error 404: Not Found"}

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
