### ISSUE TITLE
awx_web running as uid 1000 but should be 0?

### ISSUE THREAD

**Issue by MartinTerp** [geerlingguy/awx-container#7]
Hi

First, thanks for doing this, i was making this my self but you beat me to it :)

Problem:
I could not access the webinterface, eventhough the migration was complete.

When looking at the logs for awxweb, i could see:

> nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2017/09/09 14:06:35 [emerg] 81#0: mkdir() "/var/lib/nginx/tmp/client_body" failed (13: Permission denied)

And supervisor log:
> 2017-09-09 14:06:35,762 INFO exited: nginx (exit status 1; not expected)
2017-09-09 14:06:36,770 INFO gave up: nginx entered FATAL state, too many start retries too quickly

And i could see that its running under the UID 1000, eventhough root is set to UID 0 in /etc/passwd

If i added: "user: root" to the docker-compose file, under awxweb, it runs fine.
And i didt have this issue when i created the images from scratch, from the official awx repo

I also tested it on another docker instance, same issue
Both running Debian 8 ( jessie )

Have you run into this issue?

**Comment by geerlingguy** [comment]
Yes, see: https://github.com/ansible/awx/issues/89

Also, it seems when I try to set `user: root` in the compose file, I end up with no front end assets (JS or CSS) even though it seems other things load in fine :/

**Comment by MartinTerp** [comment]
Yea saw your issue on ansible/awx, but wasnt sure it was 100% related.
I dont have any problems loading assets

**Comment by geerlingguy** [comment]
Strange... I'll have to try again this morning, after resetting things locally.

**Comment by geerlingguy** [comment]
@MartinTerp - Are you on Linux, Mac, or Windows btw?

**Comment by MartinTerp** [comment]
@geerlingguy Linux Debian 8 (tried it on 2 hosts, both Debian)

**Comment by geerlingguy** [comment]
I'm testing a fresh new container locally... though being on a plane means upload will be pretty slow :D

The fix of using `user: root` in docker-compose seems to work okay, but https://github.com/geerlingguy/awx-container/issues/6 then becomes an issue. I'm testing the fix for that, and if that testing goes well, I'll push up a new container version momentarily!
